### ISSUE TITLE
Warp Pads

### ISSUE THREAD

**Issue by theminecoder** [theminecoder/mcsurvival#8]
![Example design](https://cloud.githubusercontent.com/assets/1396368/22749423/65241414-ee81-11e6-9c6c-7be8ee5fe121.png)

Ideally these warp pads will provide the server with transportation to defined areas as setup by admins or users. This will replace `/tpa` once added.

There will be public and private warps which can also be shared to friends (either a friend system or by username (uuid in storage)) to move around large distances around the map.

Only issue I can see is how we store them datawise and maintain them in game, with chunk loading/unloading,

**Comment by WesJD** [comment]
Admin warps should be globally stored, and player ones should be stored in their player data like so:
```
"warps": [
    "warpName": {
        "public": true,
        "sharedWith": []
    }
]
```
The `sharedWith` array should not be removed so if the user makes it private again, their previous people they shared it with stays.

**Comment by theminecoder** [comment]
I'm considering having so players have to place down a pad for them to create a warp point, so that it requires them to use resources each time they want to do so.

Will also need to work out recipe for this and how we work with custom items

**Comment by codenameflip** [comment]
My idea for loading the needed chunks would be to create a listener/custom event for when a player steps on a pad, and force them to wait for 5-10 seconds before teleporting; during that time the plugin could get the corresponding information about the portal the player is standing on in order to figure out where they will be going and dynamically load the chunk the destination is in.

I would fathom to guess that doing this would not cause too much lag (if any at all), as chunk loading only occurs when the player is queued to teleport 😄 

(The chunk the player was coming from _should_ automatically unload via Bukkit if there are no players in that specific chunk iirc, however you would have to investigate more on that one 😝 )

**Comment by LoonyRules** [comment]
I'd suggest having the player sneak if they want to toggle teleportation. That way, you walk onto the platform, sneak. That'll trigger the PlayerToggleSneakEvent and then you just check if there's a teleporter at that players feet and then handle it from there on. It's an easier way and it's also a confirmation from the player that they do want to travel, however, travelling doesn't have to be instant.
